name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Lint with black
              run: black --check .

            - name: Test with unittest
              run: python -m unittest discover -s tests -v
    deploy:
        runs-on: ubuntu-latest
        needs: lint-and-test
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Deploy to PythonAnywhere
              env:
                PA_USERNAME: ${{ secrets.PA_USERNAME }}
                PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
                PA_CONSOLE_ID: ${{ secrets.PA_CONSOLE_ID }}
              run: |
                pip install requests
                python deploy_to_pythonanywhere.py